# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demoLineEdit.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.labelresponse = QtWidgets.QLabel(Dialog)
        self.labelresponse.setGeometry(QtCore.QRect(30, 40, 131, 41))
        self.labelresponse.setObjectName("labelresponse")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(100, 110, 231, 51))
        self.label.setObjectName("label")
        self.lineEditName = QtWidgets.QLineEdit(Dialog)
        self.lineEditName.setGeometry(QtCore.QRect(180, 50, 113, 22))
        self.lineEditName.setObjectName("lineEditName")
        self.ButtonClicKMe = QtWidgets.QPushButton(Dialog)
        self.ButtonClicKMe.setGeometry(QtCore.QRect(100, 200, 93, 28))
        self.ButtonClicKMe.setObjectName("ButtonClicKMe")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.labelresponse.setText(_translate("Dialog", "Enter Your Name"))
        self.label.setText(_translate("Dialog", "TextLabel"))
        self.ButtonClicKMe.setText(_translate("Dialog", "Click"))
